import MiniSpectralSequences
namespace MiniSpectralSequences

/-- The motivic Adams SS (Morel-Voevodsky) over a field k:
    E_2 = Ext_{A^{mot}}(M_2, M_2) ⇒ π_{*,*}(1)∧_2.
    Bidegrees are in the motivic bigrading (s, w). -/
structure MotivicAdamsSS_Research where
  field : Type; char_zero : Prop
  ss : CohomSpectralSequence
  bigrading : String := "(s, w) where s = stem, w = weight"

/-- The motivic Steenrod algebra A^{mot} is the algebra of
    bistable operations in motivic cohomology.
    It is generated by Sq^{2i}, Sq^{2i-1}, and τ. -/
structure MotivicSteenrodAlgebra_Research where
  field : Type; char_not_2 : Prop
  generators : String := "Sq^{2i}, Sq^{2i-1}, τ"
  relations_generator : String := "τ^2 = τ·ρ + ρ·τ where ρ=[-1]"

/-- The slice filtration on the motivic sphere spectrum
    gives a spectral sequence converging to motivic stable stems.
    E_1 = π_{*,*}(s_q(1)). -/
structure SliceSS_Research where
  base_field : Type
  ss : CohomSpectralSequence
  reference : String := "Voevodsky, Röndigs-Østvær"

/-- The G-equivariant Adams SS for a finite group G:
    E_2 = Ext_{A_G}(H_*(X), H_*(pt)) ⇒ π_*^G(X). -/
structure EquivariantAdamsSS_Research where
  G : Type; finite_group : Prop; X : Type
  ss : CohomSpectralSequence
  RO_G_grading : String := "Graded on RO(G), the real representation ring"

/-- The C_2-equivariant slice SS: More tractable
    than the general equivariant case. -/
structure C2SliceSS where
  ss : CohomSpectralSequence
  bigrading : String := "RO(C_2) = Z ⊕ Z·σ"
  reference : String := "Hill-Hopkins-Ravenel, Kervaire invariant 1"

/-- The topological cyclic homology (TC) SS:
    Relates TC, THH, and TF. -/
structure TC_SS_Research where
  ring : Type; p : Nat
  ss : CohomSpectralSequence
  NikolausScholze : String := "New approach to TC via cyclotomic spectra"

/-- The prismatic cohomology SS (Bhatt-Scholze):
    Computes prismatic cohomology from a prism. -/
structure PrismaticCohomologySS where
  A : Type; p : Nat; delta_structure : Prop
  ss : CohomSpectralSequence
  Hodge_Tate_SS : String := "E_2 = H^*(Delta_{A/I}) => prismatic"

/-- The syntomic cohomology SS:
    Relates etale, crystalline, and prismatic cohomology. -/
structure SyntomicCohomologySS where
  X : Type; p : Nat
  ss : CohomSpectralSequence
  application : String := "p-adic Hodge theory"

/-- The Breuil-Kisin SS in integral p-adic Hodge theory. -/
structure BreuilKisinSS_Research where
  K : Type; perfectoid : Prop
  ss : CohomSpectralSequence

/-- The condensed spectral sequence (Scholze):
    Computes condensed cohomology of profinite sets. -/
structure CondensedSS_Research where
  S : Type; profinite : Prop
  abelian_value : Type
  reference : String := "Lectures on Condensed Mathematics, Scholze 2019"

/-- The analytic ring SS: Part of the condensed mathematics
    program, computing analytic cohomology. -/
structure AnalyticRingSS_Research where
  R : Type; analytic : Prop
  reference : String := "Clausen-Scholze, Analytic Stacks"

/-- The geometric Langlands SS:
    Relating automorphic forms to Galois representations. -/
structure GeometricLanglandsSS_Research where
  X : Type; G : Type; curve : Prop
  reference : String := "Gaitsgory et al., Proof of Geometric Langlands"

/-- The elliptic cohomology SS (Tmf):
    Computing the homotopy groups of Tmf,
    the spectrum of topological modular forms. -/
structure TmfSS_Research where
  ss : CohomSpectralSequence
  homotopy_groups : String := "pi_*(Tmf) contains modular forms"
  reference : String := "Goerss-Hopkins-Miller, Behrens"

/-- The Kervaire invariant 1 problem was solved using
    the C_2-equivariant slice SS. The answer: only in
    dimensions 2, 6, 14, 30, 62, and possibly 126. -/
structure KervaireInvariantOne where
  dimensions : List Nat := [2, 6, 14, 30, 62]
  open_126 : String := "Open in dimension 126"
  method : String := "Equivariant slice spectral sequence"
  reference : String := "Hill, Hopkins, Ravenel (2016)"

/-- Synthetic spectra: A new framework for stable homotopy
    theory based on the Yoneda embedding into a category of
    sheaves on the site of finite spectra. -/
structure SyntheticSpectraSS where
  reference : String := "Pstragowski, Synthetic Spectra"

end MiniSpectralSequences