/-
# The Fibration Exact Sequence Theorem (L4)
-/

import MiniHomotopyTheory.Core.Basic

namespace MiniHomotopyTheory

def computeFibSeq (fibTotal fibBase fibFiber : TwoComplex) (maxLen : Nat) : List Nat :=
  [fibFiber.fundamentalGroupApprox 0 maxLen |>.length,
   fibTotal.fundamentalGroupApprox 0 maxLen |>.length,
   fibBase.fundamentalGroupApprox 0 maxLen |>.length]

#eval computeFibSeq S2 S2 S1 4


end MiniHomotopyTheory

/-! ## Long Exact Sequence of a Fibration

For a Serre fibration F -> E -> B with connected base B, there is
a long exact sequence of homotopy groups:
... -> pi_n(F) -> pi_n(E) -> pi_n(B) -> pi_{n-1}(F) -> ...
-/

theorem fibration_long_exact_sequence {F E B : Type u} (p : ContinuousMap E B)
    [IsSerreFibration p] (F : Set E) (hF : p preimage {basepoint B} = F) (n : Nat) (h : n >= 1) :
    IsExactSequence (homotopyGroup F n) (homotopyGroup E n) (homotopyGroup B n)
    (homotopyGroup F (n-1)) (homotopyGroup E (n-1)) (homotopyGroup B (n-1)) := by
  -- Use the homotopy lifting property to define the boundary map delta : pi_n(B) -> pi_{n-1}(F)
  -- Exactness at pi_n(E): image of pi_n(F) = kernel of pi_n(p)
  -- Exactness at pi_n(B): image of pi_n(p) = kernel of delta
  -- Exactness at pi_{n-1}(F): image of delta = kernel of pi_{n-1}(inclusion)
  sorry

theorem hopf_fibration_homotopy_groups :
    HomotopyGroup (sphere 2) 3 = Z /\ HomotopyGroup (sphere 3) 2 = 0 := by
  -- Hopf fibration: S^1 -> S^3 -> S^2
  -- LES: pi_3(S^1) -> pi_3(S^3) -> pi_3(S^2) -> pi_2(S^1) -> pi_2(S^3) -> pi_2(S^2)
  -- =      0     ->     Z     ->  pi_3(S^2) ->    0     ->    0     ->     Z
  -- Therefore pi_3(S^2) = Z (generated by Hopf map)
  sorry

#eval "Fibration LES + Hopf"
